module Moodle2CC::Moodle2::Models
  require_relative 'models/quizzes'
  require_relative 'models/assignment'
  require_relative 'models/book'
  require_relative 'models/book_chapter'
  require_relative 'models/course'
  require_relative 'models/folder'
  require_relative 'models/forum'
  require_relative 'models/moodle2_file'
  require_relative 'models/page'
  require_relative 'models/section'
  require_relative 'models/glossary'
  require_relative 'models/glossary_entry'
  require_relative 'models/label'
end
